import React,{useState,useEffect} from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { faFacebook,faInstagram,faTwitter,faLinkedin,faGithub, fa} from '@fortawesome/free-brands-svg-icons'
import { faCoffee,faEnvelope, faExternalLinkAlt} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import MobileNav from '../components/MobileNav'
import ProjectCard from '../components/ProjectCard'


const Projects = () => {

  const [openMenu, setOpenMenu] = useState(true)
const closeMenu = () => {
  setOpenMenu(true)
}


useEffect(() => {
  setOpenMenu(true)
})

const works = [ 
  {
    title:"e-commerce",
    description:"",
    languages:[],
    github:"https://github.com/teslim191/ecommerce",
    view:"https://github.com/teslim191/ecommerce"
  },
  {
    title:"Abi's Skincare",
    description:"",
    languages:[],
    github:"https://github.com/teslim191/organicskin",
    view:"https://organicskin.herokuapp.com/"
  },
  {
    title:"url shortner",
    description:"",
    languages:[],
    github:"https://github.com/teslim191/url-shortner",
    view:"http://mylink-shortner.herokuapp.com/"
  },
  // {
  //   title:"Payment System",
  //   description:"",
  //   languages:[],
  //   github:"https://github.com/teslim191/online_payment",
  //   view:""
  // }

]

console.log(works)


  return (
    <div className='bg-[black] text-white'>
         <Head>
        <title>Teslim Jimoh - Backend Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Navbar />

      <MobileNav  />

      <div className='w-full  pt-[4rem] h-screen'>
      <h2 className="text-white text-2xl cursor-pointer text-center pb-2">SOME OF MY WORK.  
      <a href='https://github.com/teslim191' target="_blank" rel="noreferrer" >
      <span className='link hover:text-[#98dad9]'>SEE MORE </span></a>  </h2>




        <div className='flex flex-wrap justify-center '>

          <div className='w-[80%] flex-col flex flex-wrap py-4 lg:ml-[10%] lg:flex-row '>
          {works.map((work) => (

<ProjectCard work={work} key={work}  />
))}
          </div>
        </div>

        
      </div>


      {/* <Footer /> */}
 

    </div>
  )
}

export default Projects